### ISSUE TITLE
The dropdown search box on the project page is misbehaving

### ISSUE THREAD

**Issue by inodb** [Nelrohd/bootstrap-dropdown-checkbox#27]
This is what I see when I search a column name on the [project page](http://nelrohd.github.io/bootstrap-dropdown-checkbox/#). I assume this is not intended behavior? When I type the letter a in the search field I would expect to only see columns with the letter a in the dropdown box.

![dropdown_error](https://cloud.githubusercontent.com/assets/1334004/8217241/3a526738-150a-11e5-9bb6-7802546fe897.gif)

**Comment by Nelrohd** [comment]
Thank you and no, indeed. I will give a look this week.

**Comment by inodb** [comment]
Great, thank you!

**Comment by prunkstar** [comment]
I too stumbled upon this issue and had a look at it. The problem is that the dropdown is initialized with the static data you see, while the search triggers a remote search on the queryUrl ('json/exemple_1.json'). When I set the queryUrl to null (via script debugger) the filter was behaving correctly.

Btw.: Nice plugin, thank you! ;)

**Comment by Nelrohd** [comment]
Thanks for the tip and sorry, I forgot to fix it.
